all:
	pcompile main_18_v0.c mr32.c MazeMap.c AStar.c Sensors.c FollowTheWall.c DodgeObstacle.c bluetooth_comm.c FollowTheBeacon.c StopAtBeacon.c Wander.c
#	pcompile dist_test.c mr32.c MazeMap.c AStar.c Sensors.c FollowTheWall.c DodgeObstacle.c bluetooth_comm.c FollowTheBeacon.c StopAtBeacon.c Wander.c
install:
	ldpic32 -w main_18_v0.hex
#	ldpic32 -w dist_test.hex
